config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks, only: [:new, :create] do
      collection do
        get :search
      end
    end
  end

  resources :bookmarks, only: :destroy
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "This movie is already bookmarked for this list"}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @movies = Movie.all
    @list = List.find(params[:list_id])

    if @bookmark.save
      redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  def search
    search_params = params.require(:search).permit(:search)
    search_query = search_params[:search]

    @movies = Movie.where("title LIKE ?", "%#{search_query}%")
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    render 'new'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(restaurant_params)
      redirect_to lists_path, notice: "List was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="flex">
  <div class="container">
    <%= simple_form_for :search, url: search_list_bookmarks_path, method: :get do |f| %>
      <%= f.input :search, placeholder: "Search for a movie" %>
      <%= f.submit "Search" %>
    <% end %>
    <% if @bookmark.errors.count > 0 %>
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>
    <% @movies.each do |movie| %>
    <div class="movie-card">
        <%= image_tag movie.poster_url, alt: movie.poster_url, class: "cover" %>
        <div class="content">
          <h1><%= movie.title %></h1>
          <p><%= movie.overview %></p>
          <p><%= movie.rating %></p>
          <%= simple_form_for(@bookmark, url: list_bookmarks_path(@list)) do |f| %>
            <%= f.hidden_field :movie_id, value: movie.id %>
            <%= f.hidden_field :list_id, value: @list.id %>
            <%= f.input :comment %>
            <div class="flexbox">
              <%= f.submit "Add Bookmark", class: "new-list" %>
              <i class="fa-solid fa-plus fa-6x icon"></i>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner">
  <h1>Create Your Movie lists</h1>
  <%= link_to "New List +", new_list_path, class: "new-list bot-left" %>
</div>
<div class="cont">
  <div class="flex">
    <% @lists.each do |list| %>
      <div class="list-card" style="<%= list.photo.present? ? "background-image: url('#{cloudinary_url(list.photo.key, crop: :fill)}');" : "background-image: url('https://st3.depositphotos.com/4202565/32180/v/450/depositphotos_321805546-stock-illustration-movie-time-flat-concept-background.jpg');" %>">
        <h1><%= link_to list.name, list_path(list), class: "list-name" %></h1>
        <%= link_to "-", list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "remove-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="banner">
  <h1><%= @list.name %></h1>
  <div class="bot-left flex">
    <%= link_to "<- Back", lists_path, class: "new-list" %>
    <%= link_to "Add Movie +", new_list_bookmark_path(@list), class: "new-list" %>
  </div>
</div>
<div class="cont">
  <div class="flex">
    <% @list.bookmarks.each do |book| %>
      <div class="bookmark-card">
        <%= image_tag book.movie.poster_url, alt: book.movie.poster_url, class: "cover" %>
        <h1><%= book.movie.title %></h1>
        <p><%= book.comment %></p>
        <%= link_to "-", bookmark_path(book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "remove-btn" %>
      </div>
    <% end %>
  </div>
</div>